pipeline

{
    agent {
  label 'Jenkins-Dev'
}
    stages {
        stage('Build') {
            steps {
                echo 'This is a Building stage'
            }
        }
        stage('Test') {
            steps {
                echo 'This is a Testing stage'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying...'
            }
        }
    }
}