pipeline

{
    agent {
  label 'Jenkins-Dev'
}
    stages {
        stage('Build') {
            steps {
                echo 'mvn clean package'
                sh 'mvn clean package'  
                  }
        
                         
        post {
                success {
                       archiveArtifacts artifacts: '**/target/*.war'          
                        }
                
             }               
            }
}